# Generated by Django 3.2 on 2022-12-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_auto_20221205_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
